### ISSUE TITLE
TypeError: iter() returned non-iterator of type 'DataInputTest'

### ISSUE THREAD

**Issue by ucasiggcas** [zhougr1993/DeepInterestNetwork#87]
hi,dear
I met this bug in running the DIN project, the same steps as you
So what's the problem ?
```
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    print('test_gauc: %.4f\t test_auc: %.4f' % _eval(sess, model))
  File "train.py", line 131, in _eval
    for _, uij in DataInputTest(test_set, test_batch_size):
TypeError: iter() returned non-iterator of type 'DataInputTest'
```
thx

**Comment by huanypp** [comment]
May I ask how you solved it?
